[package]
name = "portexample"
version = "0.1.0"
authors = []

[lib]
name = "portexample"
path = "src/lib.rs"
crate-type = ["dylib"]

[dependencies]
rustler = "0.15.1"
rustler_codegen = "0.15.1"
lazy_static = "0.2"

[[bin]]
name = "portexample"
path = "src/lib.rs"